### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tanaes** [jlanga/khmer_trinity_snakemake#1]
Hi jlanga! 

Via the magic of Google, I was taking a look at your code to help me figure out some issues I had with [my own Snakemake implementation](https://github.com/tanaes/snakemake_shotqual) of Trimmomatic. Thank you, it was super helpful! Would you mind if I continued to use some code based off of yours? If not, would you mind adding a BSD-compatible license to your repo so we could potentially integrate it (and credit you) in some other projects?

Thanks!
-jon

**Comment by jlanga** [comment]
Hi Jon.
- First of all, sorry for the delay. I've been out of the country on holidays.
- Second, thanks for the words. It's good to see that someone has found my work and finds it useful. Usually all code is a single use product.
- Third, you are looking at my legacy code. The purpose of this repo is that I've been using it multiple times across my thesis for multiple transcriptome assemblies, and it's not correct to start using the new in recent experiments and re-do every assembly and downstream analysis again. The repo you should be looking is [smsk_khmer_trinity](https://github.com/jlanga/smsk_khmer_trinity).
- Fourth, I've been developing a framework to start from scratch snakemake pipelines with help with tools like brew, pip, etc; to make it easier to make new workflows, install dependencies, and in a future, encapsulate everything in a docker container. Code is still buggy, but it does the job. For example, I have open 3 repos that can be viewed as examples:
  - smsk_smrtanalysis: Transcriptome assembly with PacBio reads (almost finished).
  - smsk_pantherscore: Transcriptome annotation through the Panther database (WIP)
  - smsk_orthomcl: Protein clustering and phylogeny construction (WIP)
- Finally, this licensing issue is something that I have already since the beginning of the start of the smsk repo. My will is to make it completely open since I've been learning from the blog posts and tweets of innumerable people so I owe everyone, but I still have to read all the consequences of each license. On smsk it is an open issue.

Thanks,

Jorge

**Comment by jlanga** [comment]
Created a MIT license.  f5d973d  closes this.
